# Build documentation
name: Documentation Build

on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DISPLAY: ':99.0'
      DPF_IMAGE: 'docker.pkg.github.com/pyansys/dpf-core/dpf:v2021.1'
      DPF_PORT: 32772
      DPF_START_SERVER: FALSE
      DPF_DOCKER: True
      PYANSYS_OFF_SCREEN: True

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.7

      - name: Install, start, and test the virtual framebuffer
        run: |
          .ci/setup_headless_display.sh
          pip install -r .ci/requirements_test_xvfb.txt
          python .ci/display_test.py        

      - name: Install ansys.dpf.core
        run: |
          pip install ansys.grpc.dpf --extra-index-url https://$DEVOPS_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple/
          pip install -r requirements_build.txt
          pip install -e .
          cd tests
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"
        env:
          DEVOPS_PAT: ${{ secrets.DEVOPS_PACKAGES_PAT }}

      - name: Pull, launch, and validate DPF service
        run: |
          echo $PAT | docker login -u $GH_USERNAME --password-stdin docker.pkg.github.com
          docker run --restart always --name dpf -v `pwd`:/dpf -v /tmp:/dpf/_cache -p $DPF_PORT:50054 $DPF_IMAGE > log.txt &
          grep -q 'server started on ip' <(timeout 60 tail -f log.txt)
          python -c "import os; from ansys.dpf import core; core.connect_to_server(port=os.environ['DPF_PORT']); print('Python Connected')"
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          PAT: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Build Documentation
        run: |
          sudo apt install pandoc -qy
          pip install -r requirements_docs.txt
          make -C docs html
          touch docs/build/html/.nojekyll
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: docs/build/html
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true

      # - name: Deploy Documentation
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     git clone --no-checkout --depth 1 https://$GH_PAT@github.com/pyansys/pymapdl.git /tmp/gh_pages
      #     cd /tmp/gh_pages
      #     git checkout --orphan $GH_BRANCH
      #     rm -rf *
      #     git config user.name $GH_USERNAME
      #     git config user.email $GH_EMAIL
      #     cp -r $GITHUB_WORKSPACE/docs/build/html/* .
      #     touch .nojekyll
      #     git add .
      #     git commit -am "CI: Updated site via $GITHUB_SHA"
      #     git push -u origin $GH_BRANCH -f
      #   env:
      #     GH_USERNAME: ${{ secrets.GH_USERNAME }}
      #     GH_PAT: ${{ secrets.REPO_DOWNLOAD_PAT }}
      #     GH_EMAIL: ${{ secrets.GH_EMAIL }}
      #     GH_BRANCH: gh_pages
